"""
M1L1 - Structure Text and Multimodal Data with LLMs

Auto-extracted verbatim from: Structure Text and Multimodal Data with LLMs_2.ipynb
Code cells are unchanged; notebook magics are commented out.
"""


# ============================================================================
# **Lab: Structure Unstructured Restaurant Data with an LLM** | **Scenario** | Background
# ============================================================================

# %%capture
# %pip install numpy==2.3.4
# %pip install matplotlib==3.10.7
# %pip install ibm-watsonx-ai==1.4.7


# ============================================================================
# Import required libraries
# ============================================================================

import numpy as np
import matplotlib.pyplot as plt
import json
import os

# IBM WatsonX imports
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import (
    ModelTypes,
    DecodingMethods,
)

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')


# ============================================================================
# Fetch the data file
# ============================================================================

# !wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/1r_mM6ZPYNxcFv65QkzubA/California-Culinary-Map.txt


# ============================================================================
# **Exercise 1: Load the data and display the texts** | Step 1: Load the data
# ============================================================================

### Your Code Here:
### 1.1: Define the file_path to the text file
file_path = "California-Culinary-Map.txt"

### 1.2: Open the text file
with open(file_path, 'r') as file:
    data = file.read()

### 1.3: Print the first 100 characters of the restaurant data
print(data[:100])


# ============================================================================
# Step 2: Split the restaurant paragraphs into a Python list
# ============================================================================

### Your Code Here:
### 2.1: Split the restaurant paragraphs into list (hint: use .split('\n\n')
restaurant_list = data.split('\n\n')

### 2.2: Since the first item is the dataset name, we remove it
restaurant_list = restaurant_list[1:]

### 2.3: Print out the number of restaurants we have (hint: use the len() function)
print(len(restaurant_list))

### 2.4: Print out the first item to have a closer look at the content
print(restaurant_list[0])


# ============================================================================
# **Exercise 2: Define the LLM** | Step 1: Implement the LLM function
# ============================================================================

def llm_model(system_msg, prompt_txt):
    #system_msg: the system message given to the LLM
    #prompt_txt: the user prompt
    
    model_id = "ibm/granite-4-h-small"

    project_id="skills-network"

    credentials = Credentials(
                    url = "https://us-south.ml.cloud.ibm.com"
                    )

    ### 1.1: Define the model by ModelInference
    model = ModelInference(
        model_id=model_id,
        credentials=credentials,
        project_id=project_id
    )

    ### 1.2: Define the messages
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": prompt_txt}
    ]

    ### 1.3: Get the final response output and return it
    response = model.chat(messages=messages)
    output_text = response["choices"][0]["message"]["content"]
    
    return output_text


# ============================================================================
# Step 2: Test your llm_model()
# ============================================================================

import time

def safe_llm_call(system_msg, prompt_txt, retries=3):
    for i in range(retries):
        try:
            return llm_model(system_msg, prompt_txt)
        except Exception:
            time.sleep(2)
    return "Failed after retries"

system_msg = "You are a helpful assistant."
prompt_txt = "Which place is warmer in winter? Hawaii or Greenland?"
print(safe_llm_call(system_msg, prompt_txt))


# ============================================================================
# **Exercise 3: Prompt Engineering** | Step 1: Define the template
# ============================================================================

EXAMPLE_RESTAURANT_PARAGRAPH = restaurant_list[1] #use the second restaurant paragraph as the example
EXAMPLE_OUTPUT = """
    {{
    "name": "Mar de Cortez",
    "location": "Santa Monica",
    "type": "casual taqueria",
    "food_style": "Baja-style seafood",
    "rating": 4.2,
    "price_range": 1,
    "signatures": [
        "beer-battered snapper tacos",
        "zesty octopus ceviche"
    ],
    "vibe": "salt-air energy",
    "environment": "a premier sun-drenched spot for open-air dining near the pier."
    "shortcomings": []
    }}
"""

### Design your prompt here
def restaurant_data_structure_prompt_generation(restaurant_paragraph):
    base_system_msg = f"""
    You are a precise data extraction assistant that converts unstructured restaurant
    descriptions into structured JSON.

    Rules you must always follow:
    - Output ONLY a single valid JSON object. No markdown fences, no comments, no explanations.
    - Use exactly these keys: "name", "location", "type", "food_style", "rating",
      "price_range", "signatures", "vibe", "environment", "shortcomings".
    - "name", "location", "type", "food_style", "vibe", "environment" are strings.
    - "rating" is a float (e.g. 4.2).
    - "price_range" is an INTEGER equal to the NUMBER of dollar signs in the description
      ($ -> 1, $$ -> 2, $$$ -> 3, $$$$ -> 4).
    - "signatures" and "shortcomings" are lists of strings; use an empty list [] if none are mentioned.
    - Only use information present in the description. Never invent facts.
    """

    base_user_prompt = f"""
    Task:
    Read the restaurant description below and extract its attributes into the JSON schema
    shown in the example. Return only the JSON object, with no surrounding text.

    Restaurant description:
    {restaurant_paragraph}

    Example:
    Input Restaurant Description: {EXAMPLE_RESTAURANT_PARAGRAPH}
    Output:
    {EXAMPLE_OUTPUT}

    """
    return base_system_msg, base_user_prompt


# ============================================================================
# Step 2: Test your prompts
# ============================================================================

# Unit test:
restaurant_paragraph = restaurant_list[0]
base_system_msg, base_user_prompt = restaurant_data_structure_prompt_generation(restaurant_paragraph=restaurant_paragraph)

test_response = llm_model(system_msg=base_system_msg, prompt_txt=base_user_prompt)
print(test_response)


# ============================================================================
# Step 3: Validate the LLM outputs
# ============================================================================

# Validation
from pydantic import BaseModel, Field, ValidationError
from typing import List, Optional

### 3.1. Define the schema
class Restaurant(BaseModel):
    name: str
    location: str
    type: str
    food_style: str
    rating: Optional[float] = None
    price_range: Optional[int] = None
    signatures: List[str] = Field(default_factory=list)
    vibe: Optional[str] = None
    environment: str
    shortcomings: List[str] = Field(default_factory=list)


### 3.2. Use the validation method to validate the test_response from the unit test
try:
    restaurant_data = Restaurant.model_validate_json(test_response)
    print(f"Success! Validated: {restaurant_data.name}")
except ValidationError as e:
    print(f"Validation failed: {e.json()}")


# ============================================================================
# **Exercise 4: Structure all the restaurant data** | Step 1: Define prompts to have an LLM that auto repairs outputs to JSON format
# ============================================================================

def JSON_auto_repair_prompts(candidate_json_output, error_message):
    auto_repair_system_msg = """
    You are a JSON repair expert. You receive a malformed or schema-invalid JSON output
    together with the validation error it produced, and you return a corrected version.

    Rules:
    - Output ONLY the corrected JSON object. No markdown fences, no explanations.
    - Keep exactly these keys: "name", "location", "type", "food_style", "rating",
      "price_range", "signatures", "vibe", "environment", "shortcomings".
    - "rating" must be a float, "price_range" must be an integer (number of dollar signs),
      "signatures" and "shortcomings" must be lists of strings, the rest are strings.
    - Preserve all original content; only fix structure, types, keys and syntax.
      Do not invent new information. Use "" or [] if a value is genuinely missing.
    """
    auto_repair_prompt = f"""
    The following candidate JSON output failed validation.

    Candidate JSON output:
    {candidate_json_output}

    Validation error message:
    {error_message}

    Fix the issues described in the error message and return the corrected JSON object only.
    """
    return auto_repair_system_msg, auto_repair_prompt


# ============================================================================
# Step 2: Run the for loop to go over all the restaurant data in the list (approximately 20 minutes)
# ============================================================================

### Your Code Here:
structured_restaurant_lists = []
for i, restaurant_paragraph in enumerate(restaurant_list):
    ### 2.1: Produce your initial output
    base_system_msg, base_user_prompt = restaurant_data_structure_prompt_generation(
        restaurant_paragraph=restaurant_paragraph
    )
    candidate_json_output = safe_llm_call(base_system_msg, base_user_prompt)

    ### 2.2: Validation and Auto Correction loop on the output
    attempts = 0
    max_attempts = 3
    while True:
        try:
            Restaurant.model_validate_json(candidate_json_output)
            break  # valid JSON matching the schema
        except ValidationError as e:
            if attempts >= max_attempts:
                break
            attempts += 1
            repair_system_msg, repair_prompt = JSON_auto_repair_prompts(
                candidate_json_output=candidate_json_output,
                error_message=e.json()
            )
            candidate_json_output = safe_llm_call(repair_system_msg, repair_prompt)

    ### 2.3: Append your finalized response to the structured_restaurant_lists
    structured_restaurant_lists.append(candidate_json_output)

    # A manual progress bar
    if (i+1)%20 == 0:
        print(f'{i+1} out of {len(restaurant_list)} is done')

# A final message to notify the completion
print('ALL DONE!!')


# ============================================================================
# Step 3: Save the list to a JSON file
# ============================================================================

### Your Code Here:
### Print the 50th item in the structured_restaurant_lists
print(structured_restaurant_lists[49])

structured_restaurant_lists_json = [json.loads(response) for response in structured_restaurant_lists]

#For each item in the restaurant list, assign it with an itemId to be consistent with the one in the user review data:
for i, response in enumerate(structured_restaurant_lists_json):
    response['itemId'] = 1000001 + i
    structured_restaurant_lists_json[i] = response
    
filename = 'structured_restaurant_data.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(structured_restaurant_lists_json, f, indent=4)

