"""
M1L2 - Process Multimodal Data with LLMs

Auto-extracted verbatim from: M1L2_Process_Multimodal_Data_with_LLMs_FIXED.ipynb
Code cells are unchanged; notebook magics are commented out.
"""


# ============================================================================
# **Lab: Process Multimodal Data with LLMs** | **Scenario** | **Background**
# ============================================================================

# %%capture
# %pip install numpy==2.3.4
# %pip install matplotlib==3.10.7
# %pip install ibm-watsonx-ai==1.4.7


# ============================================================================
# Importing required libraries
# ============================================================================

import numpy as np
import matplotlib.pyplot as plt
import json
import os
from PIL import Image

# IBM WatsonX imports
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import (
    ModelTypes,
    DecodingMethods,
)

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')


# ============================================================================
# Fetch the data file
# ============================================================================

# !wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/hpTjb6liKBLVHQK0UgMi5A/Recipes.json
# !wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/fQUs9wQ6aB6ts6fmkD2V2w/Synthetic-User-Reviews.json
# !wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/5_Rr6ohviItzucyWk6nkrw/synthetic-recipe-images.zip

import zipfile

with zipfile.ZipFile("synthetic-recipe-images.zip", 'r') as zip_ref:
    zip_ref.extractall()


# ============================================================================
# **Exercise 1: Preprocess the food reciepe data** | Step 1: Explore the food recipe JSON File and its images
# ============================================================================

### Your Code Here
### Step 1.1: Load the json file. Define the loaded data as recipe_data.
import glob

with open('Recipes.json', 'r', encoding='utf-8') as f:
    recipe_data = json.load(f)

print(f"Number of recipes: {len(recipe_data)}")

### Step 1.2: Print each key-value pair of the first recipe. In this format: key (type of value): value
for key, value in recipe_data[0].items():
    print(f"{key} ({type(value).__name__}): {value}")

### Step 1.3: Show the image of the first recipe (recipe1)
# Build an index of every extracted image file, keyed by its file name.
# This works no matter what the folder inside the zip is called or which
# extension the images use.
ALL_IMAGE_FILES = [
    p for p in glob.glob('**/*', recursive=True)
    if p.lower().endswith(('.jpg', '.jpeg', '.png'))
]
IMAGE_INDEX = {os.path.basename(p): p for p in ALL_IMAGE_FILES}
IMAGE_STEMS = {os.path.splitext(os.path.basename(p))[0]: p for p in ALL_IMAGE_FILES}

print(f"\nImage files found: {len(ALL_IMAGE_FILES)}")
if ALL_IMAGE_FILES:
    print("Example image paths:", ALL_IMAGE_FILES[:3])


def get_recipe_image_path(recipe, index):
    """Return the path of the image file belonging to this recipe record."""
    # 1) A field in the record that already names an image file
    for value in recipe.values():
        if isinstance(value, str) and value.lower().endswith(('.jpg', '.jpeg', '.png')):
            base = os.path.basename(value)
            if os.path.exists(value):
                return value
            if base in IMAGE_INDEX:
                return IMAGE_INDEX[base]

    # 2) A field holding the image name without an extension (e.g. "recipe1")
    for value in recipe.values():
        if isinstance(value, str) and value in IMAGE_STEMS:
            return IMAGE_STEMS[value]

    # 3) Fall back to the recipe{n} naming convention
    if f'recipe{index+1}' in IMAGE_STEMS:
        return IMAGE_STEMS[f'recipe{index+1}']

    # 4) Last resort: positional match against the sorted file list
    if index < len(ALL_IMAGE_FILES):
        return sorted(ALL_IMAGE_FILES)[index]

    raise FileNotFoundError(f'No image found for recipe index {index}')


first_image_path = get_recipe_image_path(recipe_data[0], 0)
print(f"\nFirst recipe image: {first_image_path}")

img = Image.open(first_image_path)
plt.figure(figsize=(5, 5))
plt.imshow(img)
plt.axis('off')
plt.show()


# ============================================================================
# Step 2: Define the vision LLM with LLaMA
# ============================================================================

### Your Code Here: Fill in the blanks
import base64

def vision_llm(system_msg, prompt_txt, image_path):
    #system_msg: input system message for the LLM
    #prompt_txt: input user prompt for the LLM
    #image_path: the file path of the input image

    ### Credentials of the model
    model_id = 'meta-llama/llama-4-maverick-17b-128e-instruct-fp8'
    project_id="skills-network"
    credentials = Credentials(
                    url = "https://us-south.ml.cloud.ibm.com",
                    )
    generate_params = {"max_tokens": 300}

    ### Step 2.1: Define the model by ModelInference
    model = ModelInference(
        model_id=model_id,
        credentials=credentials,
        project_id=project_id,
        params=generate_params
    )

    ### Step 2.2: Encode the input image to a base64 string
    with open(image_path, 'rb') as img_file:
        encoded_image = base64.b64encode(img_file.read()).decode('utf-8')

    ### Step 2.3: Define the messages for the model
    messages = [
        {
            "role": "system",
            "content": [
                {"type": "text", "text": system_msg}
            ]
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {"url": f"data:image/jpeg;base64,{encoded_image}"}
                },
                {"type": "text", "text": prompt_txt}
            ]
        }
    ]

    ### Step 2.4: Get the response for the messages
    response = model.chat(messages=messages)
    output_text = response["choices"][0]["message"]["content"]

    return output_text


# ============================================================================
# Step 3: Design and validate prompts for the vision LLM
# ============================================================================

### Your Code Here

### Define the food image caption prompts given a food name.
### The food name, as you have noticed, comes from the corresponding recipe data.
### You want to include the food name to ensure the model focuses on it while giving captions.
def image_caption_prompt_template(food_name):
    # food_name: the food name of the recipe

    ### Step 3.1: Design the prompts
    image_caption_system_msg = (
        "You are a professional culinary photographer and food writer. "
        "You describe dishes in food images accurately, concisely and objectively. "
        "Describe only what is visible in the image: visible ingredients, cooking style, "
        "plating and presentation, colours, textures, garnishes and portion size. "
        "Do not speculate about taste, price, restaurant or nutrition, and do not add "
        "any preamble, headings or bullet points."
    )
    image_caption_prompt_txt = (
        f"The image shows a dish called '{food_name}'. "
        f"Write a single descriptive caption of 2-3 sentences for this image of '{food_name}', "
        "focusing on the visible ingredients, how it appears to be cooked, and how it is plated and presented. "
        "Return only the caption text."
    )

    return image_caption_system_msg, image_caption_prompt_txt


### Test the prompts on the first recipe
### Step 3.2: Get the prompts with the food name of the first recipe
first_recipe = recipe_data[0]
food_name = first_recipe.get('name') or first_recipe.get('food_name') or first_recipe.get('title') or first_recipe.get('recipe_name')
image_caption_system_msg, image_caption_prompt_txt = image_caption_prompt_template(food_name)

### Step 3.3: Get the test response and print it
response = vision_llm(image_caption_system_msg, image_caption_prompt_txt, first_image_path)
print(response)


# ============================================================================
# Step 4: Caption all images and augment the data
# ============================================================================

### Your Code Here:

### Get captions for each image in the dataset and add to the JSON file (up tp 15 minutes)
### recipe_data is the recipe you loaded in Step 1
for i in range(len(recipe_data)):
    if (i+1)%20 == 0:
        print(f'{i+1} out of {len(recipe_data)} is done')

    ### Step 4.1: Get the caption prompts
    recipe = recipe_data[i]
    food_name = recipe.get('name') or recipe.get('food_name') or recipe.get('title') or recipe.get('recipe_name')
    image_caption_system_msg, image_caption_prompt_txt = image_caption_prompt_template(food_name)
    image_path = get_recipe_image_path(recipe, i)

    ### Step 4.2: Get the response with the prompts
    response = vision_llm(image_caption_system_msg, image_caption_prompt_txt, image_path)

    ### Save the response as another item in the recipe data
    recipe_data[i]['image_description'] = response
print('ALL DONE!')


# ============================================================================
# Step 5: Save the image-caption-augmented recipe data
# ============================================================================

filename = 'augmented_food_recipe.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(recipe_data, f, indent=4)


# ============================================================================
# **Exercise 2: Preprocess the user visit history** | Step 1: Load the user review data
# ============================================================================

### Part 1
### Your Code Here

### Step 1.1: Load the review dataset with variable name user_review_data
with open('Synthetic-User-Reviews.json', 'r', encoding='utf-8') as f:
    user_review_data = json.load(f)

print(f"Number of user visit records: {len(user_review_data)}")

### Step 1.2: Print the first review by key-value pairs
for key, value in user_review_data[0].items():
    print(f"{key} ({type(value).__name__}): {value}")

### Part 2
### Your Code Here

### Get the image by requesting from the URL
import ast # needed to convert string representation of list to actual python list
import requests

### Convert the list of images of the first user into the actual python list
### Step 1.3: Use ast.literal_eval to convert
first_review_images = ast.literal_eval(user_review_data[0]['images'])
print(first_review_images)

### Step 1.4: Use the requests.get() method to get the image content
image_data = requests.get(first_review_images[0])

### Step 1.5: Write the image content in Step 1.4 to a temporary file 'review_image_placeholder.jpg'
with open('review_image_placeholder.jpg', 'wb') as img_file:
    img_file.write(image_data.content)

### Step 1.6: Open the 'review_image_placeholder.jpg', and show th image
review_img = Image.open('review_image_placeholder.jpg')
plt.figure(figsize=(5, 5))
plt.imshow(review_img)
plt.axis('off')
plt.show()


# ============================================================================
# Step 2: Define the prompt and the validation
# ============================================================================

### Your Code Here:
### Prompt template: caption the images with the context of the reviews
def review_context_image_caption_prompt_template(reviews):
    # reviews: the written review content

    ### Step 2.1: Design your prompts
    review_context_image_caption_system_msg = (
        "You are a culinary expert who writes concise, factual descriptions of restaurant photos. "
        "You are given a photo taken by a diner together with the written review that accompanies it. "
        "Describe only what is visible in the photo - the dishes, ingredients, plating, portion size "
        "and the surrounding setting - and use the review only as context to name dishes correctly and "
        "to reflect the diner's sentiment. Never invent details that are not visible, and return the "
        "description as plain text with no headings, bullet points or preamble."
    )
    review_context_image_caption_prompt_txt = (
        "Here is the written review associated with this photo:\n"
        f"{reviews}\n\n"
        "Using this review as context, write a single description of 2-3 sentences of the photo. "
        "Identify the dishes or setting shown, describe their appearance and presentation, and reflect "
        "the sentiment expressed in the review where the image supports it. Return only the description."
    )

    return review_context_image_caption_system_msg, review_context_image_caption_prompt_txt 

### Step 2.2: Get the prompts
first_reviews = user_review_data[0].get('reviews') or user_review_data[0].get('review') or user_review_data[0].get('text')
review_context_image_caption_system_msg, review_context_image_caption_prompt_txt = \
    review_context_image_caption_prompt_template(first_reviews)

### Step 2.3: Get the response by the vision_llm you defined previously
response = vision_llm(
    review_context_image_caption_system_msg,
    review_context_image_caption_prompt_txt,
    'review_image_placeholder.jpg'
)
print(response)


# ============================================================================
# Step 3: Caption all images and augment the data
# ============================================================================

### Your Code Here

from tenacity import retry, stop_after_attempt, wait_exponential

### URL Request function with Retry
# Retries up to 10 times, starting at 1s and doubling (1s, 2s, 4s...)
@retry(stop=stop_after_attempt(10), wait=wait_exponential(multiplier=1, min=1, max=10))
def get_data_with_retry(url):
    response = requests.get(url, timeout=5)
    response.raise_for_status() # Must raise error for retry to trigger
    return response

### Start the for loop
for i in range(len(user_review_data)):
    ### Step 3.1: Convert the string to the Python list of image urls
    review_images = ast.literal_eval(user_review_data[i]['images'])

    review_image_captions = []
    if len(review_images) > 0:
        for img_url in review_images:
            try:
                ### Step 3.2: Use get_data_with_retry to get the image_data
                image_data = get_data_with_retry(img_url)
                print("Success!")
            except Exception as e:
                print(f"All retries failed at url {img_url}:", e)
                continue
            image = image_data.content
            with open('review_image_placeholder.jpg', 'wb') as img_file:
                img_file.write(image)

            ### Step 3.3: Get the prompts, get the response, and finally append the response to review_image_captions
            reviews = user_review_data[i].get('reviews') or user_review_data[i].get('review') or user_review_data[i].get('text')
            sys_msg, prompt_txt = review_context_image_caption_prompt_template(reviews)
            caption = vision_llm(sys_msg, prompt_txt, 'review_image_placeholder.jpg')
            review_image_captions.append(caption)

    ### Append the review_image_captions to the review data
    user_review_data[i]['image_captions'] = review_image_captions
print('ALL DONE!')


# ============================================================================
# Step 4: Save the image-caption-augmented user review data
# ============================================================================

filename = 'augmented_user_review.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(user_review_data, f, indent=4)

